# Perceptron to Logistic Regression

- automatic deferenciation

## Gradient decent algorithm

```py
for each epoch:
  overall_loss = 0
  for each training example:
    pred = model(x)
    overall_loss += (pred-actual)
    
  

```

In [ ]:
import torch

In [ ]:
# Model Parameters
w_1 = torch.tensor([0.23], requires_grad=True)
b = torch.tensor([0.1], requires_grad=True)

# inputs
x_1 = torch.tensor([1.23])
y = torch.tensor([1.])

ws = x_1*w_1
ab = ws + b
print("weighted_sum + bias = ", ab)

a = torch.sigmoid(ab)
print('activation value: ', a)

weighted_sum + bias =  tensor([0.3829], grad_fn=<AddBackward0>)
activation value:  tensor([0.5946], grad_fn=<SigmoidBackward0>)


In [ ]:
import torch.nn.functional as F

l = F.binary_cross_entropy(a, y)
print(l)

tensor(0.5199, grad_fn=<BinaryCrossEntropyBackward0>)


In [ ]:
l.backward()

print('gradient of w_1 = ', w_1.grad)

gradient of w_1 =  tensor([-0.4987])


In [ ]:
class MYModel(torch.nn.Module):
  def __init__(self):
    # define model
    pass

  def forward(self, x):
    # forward pass
    # generate output
    outputs=0
    return outputs


In [ ]:
torch.manual_seed(123)
linear = torch.nn.Linear(in_features=2, out_features = 1)


In [ ]:
linear.weight

Parameter containing:
tensor([[-0.2883,  0.0234]], requires_grad=True)

In [ ]:
linear.bias

Parameter containing:
tensor([-0.3512], requires_grad=True)

In [ ]:
# single training example
x = torch.tensor([1.2, 0.5])

print(x)

tensor([1.2000, 0.5000])


In [ ]:
W = linear.weight.detach()
b = linear.bias.detach()

z = x.matmul(W.T) + b
z

tensor([-0.6855])

In [ ]:
z = linear(x)
z

tensor([-0.6855], grad_fn=<ViewBackward0>)

In [ ]:
class LogisticRegression(torch.nn.Module):
  def __init__(self, num_of_in_features):
    super().__init__()
    self.linear = torch.nn.Linear(num_of_in_features,1)

  def forward(self, x):
    logits = self.linear(x) # logits are called the weighted sum
    pred = torch.sigmoid(logits) # predictions

    return pred

In [ ]:
torch.manual_seed(1)

model = LogisticRegression(2)


In [ ]:
x = torch.tensor([1.1, 2.1])

with torch.no_grad():
  model.forward(x)

In [ ]:
from torch.utils.data import Dataset, DataLoader

class MyDataset(Dataset):

  def __init__(self, X, y):
    self.features = torch.tensor(X, dtype=torch.float32)
    self.labels = torch.tensor(y, dtype=torch.float32)

  def __getitem__(self, index):
    x = self.features[index]
    y = self.labels[index]

    return x, y

  def __len__(self):
    return self.labels.shape[0]

In [ ]:
# Downloading the dataset
#------------------------
import urllib.request
urllib.request.urlretrieve("https://raw.githubusercontent.com/Lightning-AI/dl-fundamentals/124a461c83dad576e0eaa183712fa3c16bec8b39/unit02-pytorch-tensors/2.6-revisiting-perceptron/perceptron_toydata-truncated.txt", "perceptron_toydata-truncated.txt")

('perceptron_toydata-truncated.txt',
 <http.client.HTTPMessage at 0x7ea75efefd00>)

In [ ]:
import pandas as pd

df = pd.read_csv("/content/perceptron_toydata-truncated.txt", sep="\t")
df

x1    x2  label
0   0.77 -1.14      0
1  -0.33  1.44      0
2   0.91 -3.07      0
3  -0.37 -1.91      0
4  -0.63 -1.53      0
5   0.39 -1.99      0
6  -0.49 -2.74      0
7  -0.68 -1.52      0
8  -0.10 -3.43      0
9  -0.05 -1.95      0
10  3.88  0.65      1
11  0.73  2.97      1
12  0.83  3.94      1
13  1.59  1.25      1
14  1.14  3.91      1
15  1.73  2.80      1
16  1.31  1.85      1
17  1.56  3.85      1
18  1.23  2.54      1
19  1.33  2.03      1

In [ ]:
X_train = df[["x1","x2"]].values  # getting values as matrix
y_train = df["label"].values

In [ ]:
train_ds = MyDataset(X_train, y_train)
train_loader = DataLoader(
    dataset=train_ds,
    batch_size=10,
    shuffle=True
)

In [ ]:
torch.manual_seed(1)
model = LogisticRegression(2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.05)

no_of_epoch = 20

for epoch in range(no_of_epoch):
  model = model.train()
  for batch_idx, (features, class_labels) in enumerate(train_loader):
    probas = model(features)
    loss = F.binary_cross_entropy(probas, class_labels.view(probas.shape))

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Logg
    print(f'Epoch: {epoch+1:03d}/{no_of_epoch:03d}',
          f' | Batch{batch_idx:03d}/{len(train_loader):03d}',
          f' | Loss: {loss:.2f}')



Epoch: 001/020  | Batch000/002  | Loss: 0.87
Epoch: 001/020  | Batch001/002  | Loss: 0.91
Epoch: 002/020  | Batch000/002  | Loss: 0.77
Epoch: 002/020  | Batch001/002  | Loss: 0.65
Epoch: 003/020  | Batch000/002  | Loss: 0.57
Epoch: 003/020  | Batch001/002  | Loss: 0.59
Epoch: 004/020  | Batch000/002  | Loss: 0.55
Epoch: 004/020  | Batch001/002  | Loss: 0.43
Epoch: 005/020  | Batch000/002  | Loss: 0.39
Epoch: 005/020  | Batch001/002  | Loss: 0.45
Epoch: 006/020  | Batch000/002  | Loss: 0.38
Epoch: 006/020  | Batch001/002  | Loss: 0.37
Epoch: 007/020  | Batch000/002  | Loss: 0.42
Epoch: 007/020  | Batch001/002  | Loss: 0.26
Epoch: 008/020  | Batch000/002  | Loss: 0.37
Epoch: 008/020  | Batch001/002  | Loss: 0.25
Epoch: 009/020  | Batch000/002  | Loss: 0.27
Epoch: 009/020  | Batch001/002  | Loss: 0.30
Epoch: 010/020  | Batch000/002  | Loss: 0.28
Epoch: 010/020  | Batch001/002  | Loss: 0.25
Epoch: 011/020  | Batch000/002  | Loss: 0.23
Epoch: 011/020  | Batch001/002  | Loss: 0.27
Epoch: 012

In [ ]:
def compute_accuracy(model, dataloader):
  model = model.eval()

  correct = 0.0
  total_examples = 0

  for batch_idx, (features, class_labels) in enumerate(dataloader):
    with torch.no_grad():
      pred = model(features)

    pred = torch.where(pred > 0.5, 1, 0)
    lab = class_labels.view(pred.shape).to(pred.dtype)

    compare = lab == pred
    correct += torch.sum(compare)
    total_examples += len(compare)

  return correct/total_examples


In [ ]:
train_acc = compute_accuracy(model, train_loader)

In [ ]:
print(f'Accuracy: {train_acc*100}%')

Accuracy: 95.0%


In [ ]:
# Model creation
import torch

class MyLR(torch.nn.Module):
  def __init__(self, feature_in):
    super().__init__()
    self.linear = torch.nn.Linear(feature_in, 1)

  def forward(self, x):
    logits = self.linear(x)
    preds = torch.sigmoid(logits)

    return preds

In [ ]:
model = MyLR(2)

x = torch.tensor([1.1, 2.3])
model(x)

tensor([0.5567], grad_fn=<SigmoidBackward0>)

In [ ]:
# Building a data loader
from torch.utils.data import Dataset, DataLoader

class MyData(Dataset):
  def __init__(self, features, labels):
    self.features = torch.tensor(features, dtype=torch.float32)
    self.labels = torch.tensor(labels, dtype=torch.float32)

  def __getitem__(self, index):
    x = self.features[index]
    y = self.labels[index]

    return x, y

  def __len__(self):
    return self.labels.shape[0]

In [ ]:
dset =  MyData(X_train, y_train)
d_loader = DataLoader(dset, batch_size=10, shuffle=True)

In [ ]:
import torch.nn.functional as F
# set optimizer
# epoch

model = MyLR(2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.05) # get all parameters, for training
no_of_epoch = 20

for epoch in range(no_of_epoch):
  model = model.train() # It's good to set model in train mode
  for batch_idx, (x, y) in enumerate(d_loader):
    print("Batch_id: ", batch_idx)
    print(x, " - ",y)
    pred = model(x)
    loss = F.binary_cross_entropy(pred, y.view(pred.shape)) # converting GT values to shape of predicted values's shape

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    print(f'Epoch {epoch+1 / no_of_epoch} | Batch {batch_idx / len(d_loader)} | Loss {loss}')




Batch_id:  0
tensor([[ 1.2300,  2.5400],
        [ 0.9100, -3.0700],
        [-0.6800, -1.5200],
        [-0.6300, -1.5300],
        [-0.3700, -1.9100],
        [ 1.5900,  1.2500],
        [ 3.8800,  0.6500],
        [ 0.8300,  3.9400],
        [-0.3300,  1.4400],
        [ 1.7300,  2.8000]])  -  tensor([1., 0., 0., 0., 0., 1., 1., 1., 0., 1.])
Epoch 0.05 | Batch 0.0 | Loss 0.43320322036743164
Batch_id:  1
tensor([[ 1.3100,  1.8500],
        [ 0.7300,  2.9700],
        [-0.1000, -3.4300],
        [ 1.1400,  3.9100],
        [-0.0500, -1.9500],
        [-0.4900, -2.7400],
        [ 0.7700, -1.1400],
        [ 1.3300,  2.0300],
        [ 0.3900, -1.9900],
        [ 1.5600,  3.8500]])  -  tensor([1., 1., 0., 1., 0., 0., 0., 1., 0., 1.])
Epoch 0.05 | Batch 0.5 | Loss 0.29147619009017944
Batch_id:  0
tensor([[ 1.1400,  3.9100],
        [ 0.9100, -3.0700],
        [ 1.5600,  3.8500],
        [-0.6300, -1.5300],
        [-0.0500, -1.9500],
        [-0.4900, -2.7400],
        [ 0.7300,  2.9700

In [ ]:
# def compute_accuracy(model, dataloader):
#   model = model.eval()

#   correct = 0.0
#   total_examples = 0

#   for batch_idx, (features, class_labels) in enumerate(dataloader):
#     with torch.no_grad():
#       pred = model(features)

#     pred = torch.where(pred > 0.5, 1, 0)
#     lab = class_labels.view(pred.shape).to(pred.dtype)

#     compare = lab == pred
#     correct += torch.sum(compare)
#     total_examples += len(compare)

#   return correct/total_examples


def evaluate(model, d_loader):
  model = model.eval()

  correct = 0.0
  total_examples = 0

  for batch_idx, (x, y) in enumerate(d_loader):
    with torch.no_grad():
      pred = model(x)

    pred = torch.where(pred > 0.5, 1, 0)
    lab = y.view(pred.shape).to(pred.dtype)

    compare = lab == pred
    correct += torch.sum(compare)
    total_examples += len(compare)

  return correct/total_examples

In [ ]:
acc = evaluate(model, d_loader)
print("Accuracy: ", acc)

Accuracy:  tensor(0.9500)
