# PyTorch

## What is PyTorch?

Its 3 things
- Tensor library
- Automatic differentiation engine
- Deep learning library

Its `free` and `open source`

### History of PyTorch
- `PyTorch` is based on `torch` which is another popular library written in `lua` programming language.
- Because of most people love python and don't want to learn lua, PyTorch originated from torch.
- making it available in python based on torch7
- happend in 2016
- Most likely used deep learning library for researchers

### Tensors
Mathematically: It is generalization of vectors, matrices, etc.

Computationally: as a data container for storing multi dimentional arrays

### 1. Scalar (Rank - 0 Tensor)
- In `python` its number
- Can think of it as float
```py
a = 10.
print(a)  //10.
```

In [ ]:
a = 10.
print(a) # think of it as a float

10.0



- Equivalent in `PyTorch`


In [ ]:
import torch

a = torch.tensor(10.)
a # scalar tensor or rank-0 tensor

tensor(10.)

In [ ]:
# can use a.shape to check dimentionality or rank of a Tensor
a.shape

"""
It returns nothing because its Rank-0 tensor.
"""

'\nIt returns nothing because its Rank-0 tensor.\n'

### 2. Vectors (Rank-1 Tensor)
- In Python, we can think simple list as a vector/ Rank-1 tensor


In [ ]:
a = [1., 2., 3.]
a # Vector: simple list

[1.0, 2.0, 3.0]

- In PyTorch, its same as before but wrapping the list to the `torch.tensor`


In [ ]:
a = torch.tensor([1., 2., 3.])
a # Vactor/Rank-1 Tensor

tensor([1., 2., 3.])

In [ ]:
a.shape # will return 3
# because its 3 element tensor

torch.Size([3])

### 3. Matrices (Rank-2 Tensor)
- Here we use list of lists.
- This list has two sub list, and each of the sub list represents the row, So this will result in a matrix consisting of 2 rows and 3 columns.
- We can think of the rows as a `training example`, and columns represnts the `features` of the dataset

In [ ]:
a = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
a.shape

torch.Size([2, 3])

### Considering realworld dataset
- We can think image as a matrix

<img src="https://images.pexels.com/photos/539694/pexels-photo-539694.jpeg" width="400" >

- Where the rows and the columns represents the pixels of the image.
- Here the image refers to 1 training example

**Look at RGB image**

Red, green, blue, 3 different color channels

- So, in above image we have 3 color channels rgb.
- we can think of this as a `stack of matrices`.
- each layer/color channel represents the matrix.
- as we already know scalar(rank-0 tensor), vectors(rank-1 tensor), and matrices(rank-2 tensors).

### 4. 3D-tensors
- So we this 3 dimentional data we call it **3D-tensor**
- We can think stack of matrices as a 3D tensors




In [ ]:
a = torch.tensor([[[1., 2., 3.],[2., 3., 4.]],
                  [[4., 5., 6.], [7., 8., 9.]]])
a

tensor([[[1., 2., 3.],
         [2., 3., 4.]],

        [[4., 5., 6.],
         [7., 8., 9.]]])

In [ ]:
"""
So, when we use a.shape it returns 3 numbers
- each number represents one dimention or one rank,
- and then numbers represents the values in this dimention
"""
a.shape

torch.Size([2, 2, 3])

### 5. 4D(rank-4)tensor

Going 1 step further we can also have a stack of multiple color images.

this would add another dimention.

And in this case we have 4 dimentional tensor or rank-4 tensor

In [ ]:
b = torch.stack((a, a))
b

tensor([[[[1., 2., 3.],
          [2., 3., 4.]],

         [[4., 5., 6.],
          [7., 8., 9.]]],


        [[[1., 2., 3.],
          [2., 3., 4.]],

         [[4., 5., 6.],
          [7., 8., 9.]]]])

In [ ]:
b.shape

torch.Size([2, 2, 2, 3])

So it looks similar like numpy's array, now let's see how tensor is different than a numpy array.


## Comparing Tensor library with Array library

- they are actually the same thing.
- tensor library = array library
- torch.tensor ~= numpy.array: torch.tensor is almost identical to numpy.array

Difference

|torch.tensor|
|:-|
|+ supports GPU computation|
|+ Automatic differentiation support, very useful when training neural nets|

### How tensors and arrays differe from regular python lists?

**Python Lists**
+ **Pros:** Can store heterogeous types (mix str, float, etc). you can store float, strings, and other objects mixed in a list.
+ **Pros:** In python list we can easily remove or add items using `.append` or `.pop`
+ **Cons:** while lists are easy to use and flexible, lists are very slow when it comes to numerical computation(that is the main motivation behind tensors)

**Tensors**
- Limitations of using tensors though is that all elements in tensors have to be the same type(eg. float, integer)
- In contrast to lists, tensors also have a fixed size, so we can't easily add or remove If we want to have a larger tensor, we have to create new empty tensor with a larger size and copy over the all the elements and add the new elements to it

this sounds like tensors are bad, However tensors have certain advantages over the lists which are extreamly useful for deep learning, which is heavily based on numerical computations.

- tensors support wide variety of different computations.
- numerical computations are fast

# Using Tensors In PyTorch

1. `torch.tensor()`: Creating Tensors
    - its most fundamental function. bcs that's how we create a tensors in PyTorch

In [ ]:
a = torch.tensor([1., 2., 3.])
a

tensor([1., 2., 3.])

2. `.shape` Checking Shape of Tensors
    - tensor.shape to check the shape of the tensor.
    - using `.shape` attribute we can check the no of elements in the tensor.
    - in 2D tensor 1st no referes no of rows in tensor, and 2nd no referes no of columns in tensor.
    - to check rank of the tensor count the no of no that are returned by `.shape`

In [ ]:
a = torch.tensor([[1., 2., 3.], [3., 4., 5.]])
a

tensor([[1., 2., 3.],
        [3., 4., 5.]])

In [ ]:
a.shape # will get [2,3] tow numbers meaning its 2D tensor

torch.Size([2, 3])

3. `.ndim`: Checking the Rank/ Number of Dimentions
    - use .ndim to check rank or dimention of the tensor

In [ ]:
a = torch.tensor([[[1., 2., 3.], [4., 5., 6.]], [[3., 4., 5.], [6., 7., 8.]]])
a

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[3., 4., 5.],
         [6., 7., 8.]]])

In [ ]:
a.ndim # will get dimention of the tensor, in our case its 3D tensor

3

4. `.dtype`: Checking the Data type of Tensor
    - as tensor can only store same type of data.
    - we can see the datatype of the tensor.
    - below it returns torch.float32, meaning 32 bit precision
    - that's prefered precision in deep learning bcs of efficiency reasons

In [ ]:
a = torch.tensor([[1., 2., 3.], [5., 6., 7.]])
a

tensor([[1., 2., 3.],
        [5., 6., 7.]])

In [ ]:
a.dtype # will get data type of tensor that is float32

torch.float32

In [ ]:
a = torch.tensor([[1,2,3],[4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
a.dtype # int datatype

torch.int64

5. `torch.from_numpy(np_array)` Creating Tensor from Numpy Array
    - torch has the `from_numpy()` function which lets us convert Numpy array directly into Tensor.
    - can also call `.tensor` on numpy array, but that would create a copy in memory.
    - using from_numpy() function it will use the same memory as the numpy array.
    - since python uses 64bit precision bydefault, the converted tensor from numpy will be the same 64bit.


In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1., 2., 3.]) # creating numpy array
print(f"Numpy array: {np_array}")
m2 = torch.from_numpy(np_array) # creating tensor from numpy array, its dtype will be same as numpy's that is 64bit,
# its 64 because its default type in numpy
m2

Numpy array: [1. 2. 3.]


tensor([1., 2., 3.], dtype=torch.float64)

6. `tensor_obj.to(new_dtype)` Change the dtype

In [ ]:
m2 # currently its float64 dtype

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
m2 = m2.to(torch.float32) # changing 64bit datatype to 32
m2.dtype

torch.float32

7. `.device` Checking the device Type
    - tensors also have a `.device` attribute, that show us where on our computer the tensor is located.
    - So usually it will return CPU which means tensor is on CPU's memory.
    - Later will see how to transfer tensors to the GPU which can be very useful for deep learnig and accelerating training.

In [ ]:
m2.device # currently its on cpu

device(type='cpu')

8. Changing Shape of a Tensor


In [ ]:
print(a.shape)
a

torch.Size([2, 3])


tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
a.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
a.view(-1,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

9. Transposing a Matrix


In [ ]:
m = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
m

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
m.T

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])